- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/SideTabComponent.vue
- frontend/src/main.js
- frontend/src/pages/LoginPage.vue
- 사이드 탭 컴포넌트 html/css 개발
- PrimeVue 라이브러리를 적용해서 개발을 진행
- 로그인 페이지에서 테스트를 진행했고 코드를 주석으로 처리했습니다.
- 추후 사이드 탭을 적용할 때 로그인 페이지에 주석으로 처리된 코드를 사용하시면 됩니다.
close #43
> [Feat] 사이드 탭 컴포넌트 개발(#43)

- .idea/inspectionProfiles/Project_Default.xml
- frontend/src/App.vue
- frontend/src/component/HeaderComponent.vue
- 헤더컴포넌트개발
- 버튼 구성 시 아이콘 대체 필요 Fixes: #45
확인부탁드립니다.
> [Feat] HeaderComponent 개발 (#45)

- frontend/src/main.js
- frontend/src/pages/LoginPage.vue
- 채팅방 나가기 모달창 html/css 개발
- PrimeVue에서 ConfirmDialog를 이용하여 채팅방 나가기 확인 모달 창 개발
- 로그인 페이지에서 테스트를 진행했고 주석으로 처리하여 추후 사용 예정
close #39
> [Feat] 채팅방 나가기 모달창 개발(#39)

- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
- MainPage 개발 Resolves: #38 
- headercomponent, sidebarcomponent 활용완료
- 채팅입력컴포넌트 이식 필요,
- 채팅내용 컴포넌트 개발 필요
> [Feat] MainPage 개발 (#38)

- frontend/src/components/MeetingRoomCompornent.vue
- 회의실 현황 html/css 작성
- 추후 데이터 적용
> [Feat] 회의실 현황 컴포넌트 개발 (#37)

- .idea/modules.xml
- backend/pom.xml
- backend/src/main/java/com/project/ssm/chat/config/QueryDslConfig.java
- backend/src/main/java/com/project/ssm/chat/config/WebSocketBrokerConfig.java
- backend/src/main/java/com/project/ssm/chat/controller/ChatController.java
- backend/src/main/java/com/project/ssm/chat/controller/ChatRoomController.java
- backend/src/main/java/com/project/ssm/chat/model/entity/ChatRoom.java
- backend/src/main/java/com/project/ssm/chat/model/request/PatchUpdateRoomReq.java
- backend/src/main/java/com/project/ssm/chat/model/response/DeleteRoomRes.java
- backend/src/main/java/com/project/ssm/chat/model/response/GetChatListRes.java
- backend/src/main/java/com/project/ssm/chat/model/response/PatchUpdateRoomRes.java
- backend/src/main/java/com/project/ssm/chat/repository/ChatRoomRepository.java
- backend/src/main/java/com/project/ssm/chat/repository/MessageRepository.java
- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustom.java
- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustomImpl.java
- backend/src/main/java/com/project/ssm/chat/service/MessageService.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- backend/src/main/java/com/project/ssm/config/QueryDslConfig.java
- frontend/src/App.vue
- frontend/src/components/ChatBlockComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/main.js
- frontend/src/pages/CalendarPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
채팅방 관련 기능 개발
- 채팅방 생성 기능 개발 (#11)
- 채팅방 접속 시 필요한 stomp 연결을 pinia 상태 관리를 통해서 처리할 수 있게 변경
close #11
> [Feat] 채팅방 관련 기능 개발 (#11)

- backend/src/main/java/com/project/ssm/chat/controller/ChatRoomController.java
- backend/src/main/java/com/project/ssm/chat/model/request/PostCreateRoomReq.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- 채팅방 수정 기능 개발 (#13)
- 채팅방 삭제 기능 개발 (#14)
- 채팅방 나가기 기능 개발 (#15)
- 메시지 삭제 기능 개발 (#18)
> [Feat] 채팅방 관련 기능 개발 (#13, #14, #15, #18)

- .idea/modules.xml
- backend/src/main/java/com/project/ssm/event/controller/EventsController.java
- backend/src/main/java/com/project/ssm/event/exception/Exception.java
- backend/src/main/java/com/project/ssm/event/service/EventsService.java
- backend/src/main/java/com/project/ssm/meetingroom/controller/MeetingRoomController.java
- backend/src/main/java/com/project/ssm/meetingroom/exception/Exception.java
- backend/src/main/java/com/project/ssm/meetingroom/service/MeetingRoomService.java
- backend/src/main/java/com/project/ssm/search/controller/SearchController.java
- backend/src/main/java/com/project/ssm/search/exception/Exception.java
- backend/src/main/java/com/project/ssm/search/model/request/ChatSearchReq.java
- backend/src/main/java/com/project/ssm/search/service/SearchService.java
- frontend/src/components/MeetingRoomCompornent.vue
- frontend/src/components/MemberSearchComponent.vue
- frontend/src/components/ReservationComponent.vue
> [Refactor] 예약, 회의실, 유저검색 컴포넌트 리펙토링 (#37,#40)

- frontend/public/index.html
- frontend/src/components/CalendarComponent.vue
- frontend/src/components/FullCalendarComponent.vue
- frontend/src/pages/LoginPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- 라우터를 활용하여 페이지 인증확인 기능 추가
- 메인페이지, 로그인페이지 html css 수정 Fixes: #38
> [Feat] 라우터 인증 기능 추가 (#38)

- backend/src/main/java/com/project/ssm/member/config/filter/JwtFilter.java
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/components/CalendarComponent.vue
- frontend/src/components/MeetingRoomCompornent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/main.js
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- 각 컴포넌트 연결
- html, css 수정 Fixes: #38
> [Refactor] 메인페이지 및 사이드바 리팩토링 (#38)

- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationDuplicateException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationNotFoundException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationOverException.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- backend/src/main/java/com/project/ssm/meetingroom/controller/MeetingRoomController.java
- backend/src/main/java/com/project/ssm/meetingroom/exception/MeetingDuplicateException.java
- backend/src/main/java/com/project/ssm/meetingroom/exception/MeetingRoomNotFoundException.java
- backend/src/main/java/com/project/ssm/meetingroom/model/response/MeetingRoomAddRes.java
- backend/src/main/java/com/project/ssm/meetingroom/model/response/MeetingRoomAddResult.java
- backend/src/main/java/com/project/ssm/meetingroom/model/response/MeetingSelectRes.java
- backend/src/main/java/com/project/ssm/meetingroom/model/response/MeetingSelectResMeetingRoomSelectResult.java
- backend/src/main/java/com/project/ssm/meetingroom/model/response/MeetingSelectResReservation.java
- backend/src/main/java/com/project/ssm/meetingroom/repository/MeetingRoomRepository.java
- backend/src/main/java/com/project/ssm/meetingroom/service/MeetingRoomService.java
> [Refactor] 회의실 내부클래스 외부로변경 및 변경으로 인한 서비스와 컨트롤러 수정 및 예외처리 추가

- backend/src/main/java/com/project/ssm/chat/controller/ChatRoomController.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- backend/src/main/java/com/project/ssm/member/config/filter/JwtFilter.java
- frontend/src/components/SidebarComponent.vue
- frontend/src/stores/useChatRoomStore.js
- 기존의 채팅방 생성시 ChatRoom이 정상적으로 생성되지 않을 상태에서 다른 엔티티에 저장하려고 시도하여 발생하는 문제 해결
> [Refactor] 채팅방 생성 기능 개선

- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/events/controller/EventController.java
- backend/src/main/java/com/project/ssm/events/model/entity/Event.java
- backend/src/main/java/com/project/ssm/events/repository/EventCustomRepository.java
- backend/src/main/java/com/project/ssm/events/repository/EventRepository.java
- backend/src/main/java/com/project/ssm/events/repository/EventRepositoryImpl.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- frontend/public/js/addEvent.js
- frontend/public/js/main.js
일정 관련 기능 코드 리팩토링
일정 등록과 조회 프론트 백 연동했습니다
> [Refactor] 일정 관련 기능 리팩토링

- backend/src/main/java/com/project/ssm/events/controller/EventController.java
- backend/src/main/java/com/project/ssm/events/model/request/MeetingRoomReqMemberRequest.java
- backend/src/main/java/com/project/ssm/events/model/request/MeetingRoomReservationReq.java
- backend/src/main/java/com/project/ssm/events/model/response/MeetingRoomReservationRes.java
- backend/src/main/java/com/project/ssm/events/model/response/MeetingRoomReservationResResult.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
> [Refactor]내부 클래스 외부로 수정 및 그에따른 서비스 수정

- frontend/public/js/addEvent.js
- frontend/public/js/editEvent.js
- frontend/public/js/main.js
- frontend/src/components/CalendarComponent.vue
- frontend/src/components/FilterComponent.vue
- frontend/src/components/FullCalendarComponent.vue
- frontend/src/pages/MainPage.vue
> [Refactor] 메인페이지 일정 CRUD 프론트 연동 (#38)

- cicd/k8s/backend/back-service.yml
- cicd/k8s/backend/backend-deployment.yml
- cicd/k8s/backend/cm-ssm-backend.yml
- cicd/k8s/db/db-config.yml
- cicd/k8s/db/mariadb-pod.yml
- cicd/k8s/db/mariadb-service.yml
- cicd/k8s/frontend/front-service.yml
- cicd/k8s/frontend/frontend-deployment.yml
- frontend/nginx/default.conf
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 프론트엔드 메니페스트 작성
- 백엔드 메니페스트 작성
- DB 메니페스트 작성
- nginx 프록시 설정으로 인한 프론트에서 사용하는 백엔드 주소 변경
> [Feat] k8s 메니페스트 파일 작성 (#19, #20, #21, #22) 

- backend/src/test/java/com/project/ssm/meetingroom/controller/MeetingRoomControllerTest.java
- 백엔드 회의실 생성 및 조회 테스트 코드 작성(#91)
> [Test] 회의실 생성 조회 테스트 코드 작성(#91)

- backend/backend-deployment.yml
- cicd/jenkins/backpipe.txt
- cicd/jenkins/frontpipe.txt
- frontend/frontend-deployment.yml
- frontend/public/index.html
- 프론트엔드 젠킨스 파이프라인 작성 #23 
- 백엔드 젠킨스 파이프라인 작성 #78
> [Feat] jenkins 파이프라인 작성 (#23 #78) 

- frontend/Dockerfile
- 프론트엔드 Dockerfile에서 dist 폴더 내용 수정
> [Fix] 프론트엔드 Dockerfile 수정

- backend/backend-deployment.yml
- frontend/frontend-deployment.yml
- k8s 백엔드 메니페스트 readinessProbe 수정
- k8s 프론트엔드 메니페스트 readinessProbe 수정
> [Fix] k8s 메니페스트 수정

- backend/src/test/java/com/project/ssm/meetingroom/controller/MeetingRoomControllerTest.java
- cicd/jenkins/backpipe.txt
- cicd/jenkins/frontpipe.txt
- frontend/package-lock.json
- frontend/package.json
- frontend/test-results/report.xml
- 백엔드 및 프론트엔드 파이프라인 파일 수정
- 스프링 부트 테스트 코드 수정
> [Refactor] jenkins 파이프라인 파일 수정 및 테스트 코드 수정

- frontend/package-lock.json
- frontend/src/components/SidebarComponent.vue
- frontend/src/stores/useChatRoomStore.js
- 채팅방 리스트 조회 부분 수정
- roomList를 받는 부분을 수정
> [Refactor] SidebarComponent 수정

- backend/src/main/java/com/project/ssm/events/repository/EventRepositoryImpl.java
- backend/src/main/java/com/project/ssm/member/controller/MemberController.java
- backend/src/main/java/com/project/ssm/member/repository/MemberCustomRepository.java
- backend/src/main/java/com/project/ssm/member/repository/MemberRepository.java
- backend/src/main/java/com/project/ssm/member/repository/MemberRepositoryImpl.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- backend/src/main/java/com/project/ssm/notification/Scheduler.java
- frontend/src/components/MeetingRoomCompornent.vue
- frontend/src/pages/ChangeInfoPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- 비밀번호 및 프로필사진 변경 페이지 추가 Fixes: #33
> [Feat] 비밀번호 변경페이지 추가(#33)

- backend/src/main/java/com/project/ssm/events/service/EventService.java
- frontend/public/js/main.js
- frontend/src/components/HeaderComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- 채팅 블럭 컴포넌트 중복 조회가 되는 부분 개선
- 채팅방 목록 컴포넌트 중복 조회가 되는 부분 개선 (#42)
> [Refactor] 채팅 기능 리펙터링 (#42)

- frontend/src/pages/ErrorPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMessageStore.js
- 라우터를 사용하여 에러 페이지의 에러 코드 및 설명 추가
- 채팅방 조회 에러 발생시 예외 처리
> [Refactor] 에러 페이지 수정 및 예외 처리 추가

- frontend/src/components/CalendarComponent.vue
> [Feat] 캘린더 컴포넌트 일정현황 개발(#35)

- frontend/public/js/addEvent.js
- frontend/src/App.vue
- frontend/src/components/FullCalendarComponent.vue
- frontend/src/main.js
- frontend/src/pages/ChangeInfoPage.vue
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- 일정등록 Fixes: #38
일정등록 프론트 부분입니다.
> [Refactor] 일정등록 (#38)

- backend/src/main/java/com/project/ssm/events/controller/EventController.java
- backend/src/main/java/com/project/ssm/events/model/response/PatchReservationRes.java
- backend/src/main/java/com/project/ssm/events/model/response/PostEventRes.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- frontend/public/js/addEvent.js
- frontend/src/components/ReservationComponent.vue
- 일정 등록 기능에서 회의실이 null값이어도 등록되게 변경했습니다.
> [Refactor] 일정 등록 기능 프론트, 백 코드 리팩토링 (#6, #34)

- frontend/src/components/MeetingRoomCompornent.vue
- frontend/src/components/ReservationComponent.vue
- frontend/src/stores/useMainStore.js
- 회의실 컴포넌트에서 실시간으로 회의실 이용가능 여부를 확인할 수 있도록 수정했습니다.
> [Refactor] 회의실 컴포넌트 리팩토링 (#37)

- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/member/controller/MemberController.java
- backend/src/main/java/com/project/ssm/member/exception/MemberAccountException.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.js
- frontend/src/pages/ChangeInfoPage.vue
- frontend/src/pages/LoginPage.vue
- frontend/src/pages/SignUpPage.vue
- frontend/src/stores/useMemberStore.js
> [Feat] 아이디 중복확인 추가 (#38)

- frontend/src/pages/SignUpPage.vue
- 아이디 중복확인 후 아이디 입력 disabled
- develop merge 후 다시 푸시
Fixes: https://github.com/beyond-sw-camp/be02-fin-LAT32T-SSM/issues/38
> [Refactor] 아이디 중복확인 추가 (#38)

- frontend/.env.development
- frontend/.env.production
- frontend/public/index.html
- frontend/public/js/addEvent.js
- frontend/public/js/editEvent.js
- frontend/public/js/main.js
- frontend/src/components/ReservationComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 개발과 배포가 편하게끔 환경변수 추가 Fixes: #38
> [Refactor] 빌드환경구성기능 추가 (#38)

- frontend/src/components/CalendarComponent.vue
- frontend/src/stores/useMainStore.js
> [Refactor] 날짜클릭시 일정현황 타이틀 반환

- backend/src/main/java/com/project/ssm/events/model/entity/Event.java
- backend/src/main/java/com/project/ssm/events/repository/EventCustomRepository.java
- backend/src/main/java/com/project/ssm/events/repository/EventRepositoryImpl.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- backend/src/main/java/com/project/ssm/events/utils/EventsOfDate.java
- backend/src/main/java/com/project/ssm/meetingroom/service/MeetingRoomService.java
- backend/src/main/java/com/project/ssm/meetingroom/utils/CurrentMeetingRoom.java
- backend/src/main/java/com/project/ssm/member/repository/MemberRepository.java
- backend/src/main/resources/application.yml
> [Refactor] 일정 상세 조회 기능 리팩토링 (#8)

- .idea/misc.xml
- backend/src/main/java/com/project/ssm/search/model/response/MemberSearchRes.java
- backend/src/main/java/com/project/ssm/search/service/SearchService.java
- frontend/public/js/etcSetting.js
- frontend/public/js/main.js
- frontend/src/components/FilterComponent.vue
- frontend/src/components/FullCalendarComponent.vue
- frontend/src/components/MemberSearchComponent.vue
- frontend/src/stores/useMainStore.js
> [Refactor] mainpage 개선 (#38)

- backend/src/main/java/com/project/ssm/notification/Scheduler.java
> [Refactor] 일정 기능 리팩토링

- backend/pom.xml
- backend/src/main/java/com/project/ssm/events/repository/EventRepositoryImpl.java
- backend/src/main/java/com/project/ssm/notification/KafkaConfig.java
- backend/src/main/java/com/project/ssm/notification/NotificationController.java
- backend/src/main/java/com/project/ssm/notification/NotificationService.java
- backend/src/main/java/com/project/ssm/notification/Scheduler.java
- backend/src/main/resources/application.yml
- 서버 scale out 시 kafka를 통해 통신 기능 추가
- 그룹아이디 동적으로 변경
- application.yml에 bootstrap-servers 추가
> [Feat] kafka 통신기능 추가 (#156)

- backend/src/main/java/com/project/ssm/chat/controller/ChatController.java
- backend/src/main/java/com/project/ssm/config/web/WebSocketBrokerConfig.java
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useStompStore.js
- 백엔드 stomp 메시지 브로커 설정 부분 수정
- 프론트엔드 stomp client 부분 코드 수정
- 백엔드와 웹 소켓 연결 주소 변경
> [Refactor] 채팅 기능 수정 및 stomp 연결 수정Frontend/feature/chatting

- backend/src/main/java/com/project/ssm/common/error/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/project/ssm/events/controller/EventController.java
- backend/src/main/java/com/project/ssm/events/repository/EventCustomRepository.java
- backend/src/main/java/com/project/ssm/events/repository/EventRepositoryImpl.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- backend/src/main/java/com/project/ssm/notification/controller/NotificationController.java
- backend/src/main/java/com/project/ssm/notification/service/NotificationService.java
- backend/src/main/java/com/project/ssm/utils/Scheduler.java
- frontend/public/js/main.js
- 기존 1년 단위로 일정 조회 하는 것을 프론트에 떠있는 달력의 시작과 끝점만 조회할 수 있도록 변경
- SCDF와 배치시스템 적용에 따른 메인서버에서 스케쥴링기능 off
- 기타 코드 정리
> [Refactor] 일정 조회 기능변경

- backend/src/main/java/com/project/ssm/notification/controller/NotificationController.java
- frontend/src/components/HeaderComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/pages/ChangeInfoPage.vue
- frontend/src/pages/LoginPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/SignUpPage.vue
- frontend/src/stores/useStompStore.js
- login 페이지 css 변경
- 메인페이지 달력 위치 고정
- 메인페이지 헤더 내용 수정
- 메인페이지 사이드바 채널클릭시 화살표 모양 수정
- 회원정보수정페이지연결
- 채팅입력시 스크롤 가장 밑으로 내려가게 수정
- 배치서버에서 보내는 topic 받을 수 있게 listener topic 수정
> [Refactor] 메인페이지 CSS 수정

- backend/src/main/java/com/project/ssm/notification/controller/NotificationController.java
- frontend/nginx/default.conf
> [Fix] Nginx 설정 변경

- frontend/src/components/HeaderComponent.vue
- frontend/src/stores/useMainStore.js
> [Fix] 로그아웃 시 알람오는 문제 해결

- backend/src/main/java/com/project/ssm/chat/model/entity/ChatRoom.java
- backend/src/main/java/com/project/ssm/member/controller/MemberController.java
- backend/src/main/java/com/project/ssm/member/model/response/GetChatRoomMembersRes.java
- backend/src/main/java/com/project/ssm/member/repository/MemberCustomRepository.java
- backend/src/main/java/com/project/ssm/member/repository/MemberRepositoryImpl.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/src/components/FilterComponent.vue
- frontend/src/stores/useMainStore.js
- 필터 채팅방 list 선택 시 채팅방에 참가한 멤버만 나오게 수정
- ChatRoomName unique로 수정
> [Feat] 채팅방list 선택시 기능 추가

- backend/src/main/java/com/project/ssm/chat/model/entity/ChatRoom.java
- backend/src/main/java/com/project/ssm/member/controller/MemberController.java
- backend/src/main/java/com/project/ssm/member/exception/MemberNotFoundException.java
- backend/src/main/java/com/project/ssm/member/repository/MemberCustomRepository.java
- backend/src/main/java/com/project/ssm/member/repository/MemberRepositoryImpl.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/public/js/main.js
- frontend/src/components/FilterComponent.vue
- frontend/src/stores/useMainStore.js
- 필터 채팅방 list 선택 시 채팅방에 참가한 멤버만 나오게 기능수정
- ChatRoomName 중복가능하게 수정
- 예외처리
> [Refactor] 채팅방list 선택시 기능 수정

- frontend/src/components/CreateChatRoomComponent.vue
- frontend/src/components/FilterComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
> [Refactor] 채팅방 생성 모달창 수정

- backend/src/main/java/com/project/ssm/chat/exception/ChatRoomAccessException.java
- backend/src/main/java/com/project/ssm/chat/exception/ChatRoomDuplicateException.java
- backend/src/main/java/com/project/ssm/chat/exception/MessageDuplicateException.java
- backend/src/main/java/com/project/ssm/chat/exception/MessageNotFoundException.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- backend/src/main/java/com/project/ssm/member/exception/MemberAccountException.java
- backend/src/main/java/com/project/ssm/member/exception/MemberDuplicateException.java
- backend/src/main/java/com/project/ssm/member/exception/MemberNotFoundException.java
- backend/src/main/java/com/project/ssm/utils/JwtUtils.java
- frontend/src/components/SidebarComponent.vue
- frontend/src/pages/ErrorPage.vue
- frontend/src/pages/LoginPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/SignUpPage.vue
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 채팅방 기능 관련 예외처리 추가
- 채팅 기능 관련 예외처리 추가
- 멤버 기능 관련 예외처리 추가
- 멤버 예외처리 메시지 한국어로 변경
> [Refactor] 채팅방, 채팅, 멤버 관련 예외 처리 추가 및 수정

- backend/src/main/java/com/project/ssm/chat/service/MessageService.java
- backend/src/main/java/com/project/ssm/notification/controller/NotificationController.java
- backend/src/main/java/com/project/ssm/notification/service/EmittersService.java
- SseEmitter 주입 필요가 많아짐에 따라 service로 분리
> [Refactor] 채팅 알림 기능 수정 (#72)

- backend/src/main/java/com/project/ssm/chat/controller/ChatController.java
- backend/src/main/java/com/project/ssm/chat/controller/ChatRoomController.java
- backend/src/main/java/com/project/ssm/chat/model/request/PatchUpdateRoomReq.java
- backend/src/main/java/com/project/ssm/chat/service/MessageService.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- 요구사항 정의서에 맞게 변수명 수정
- 필요없는 주석 부분 제거
> [Fix] 요구사항 정의서에 맞게 변수명 변경

- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustomImpl.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- frontend/src/components/ChatBlockComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 채팅컴포넌트 프로필 이미지 로드 안되는 문제 해결
- 채팅방 입장 시 빈 알람 뜨는 문제 해결
- 채팅을 길게 쳤을때 의도치 않게 줄바꿈 되는 문제 해결
- 채팅방 입장 시 최신채팅내용 10개가 밑에서부터 위로 불러와지게 해결
- 같은 채팅방 여러번 입장 시 중복 구독을 하게 돼서 중복된 구독수 만큼 채팅컴포넌트가 나왔던 문제 해결
> [Refactor] 채팅 관련 기능 수정

- backend/src/main/java/com/project/ssm/chat/controller/ChatController.java
- backend/src/main/java/com/project/ssm/chat/model/entity/ChatRoom.java
- backend/src/main/java/com/project/ssm/chat/model/entity/Message.java
- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustom.java
- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustomImpl.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
- frontend/src/pages/SignUpPage.vue
- frontend/src/stores/useMemberStore.js
> [Refactor] 회원가입 예외처리 추가

- backend/src/main/java/com/project/ssm/chat/service/MessageService.java
- backend/src/main/java/com/project/ssm/chat/service/RoomService.java
> [Refactor] 채팅방,채팅 기능 필요 없는 주석 제거

- backend/src/main/java/com/project/ssm/chat/service/MessageService.java
- backend/src/main/java/com/project/ssm/notification/controller/NotificationController.java
- backend/src/main/java/com/project/ssm/notification/service/EmittersService.java
- frontend/src/stores/useMainStore.js
- SseEmitter 중복되는 코드 메서드로 정리
- 메세지 알람시 '멤버이름: 메세지' 형식으로 변경
- 이벤트리스너 요청 시 서버가 응답하지 못할 때 5번 시도 후 이벤트리스너 close 기능 추가
> [Refactor] 코드 refactor 및 이벤트리스너 예외처리

- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/src/pages/Error404Page.vue
- frontend/src/pages/MainPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 각 기능마다 발생할 수 있는 예외처리 코드를 추가
- 멤버 프로필 이미지 가져오는 기능 예외처리 추가
- 404 에러 페이지 추가
- url 경로 정규 표현식 추가
>  [Refactor] 전체적인 예외 처리 코드를 추가

- frontend/tests/unit/Event.spec.js
- frontend/tests/unit/chatRoom.spec.js
- frontend/tests/unit/signup.spec.js
- 채팅방 프론트엔드 테스트 코드 개발 (#88)
- 일정 기능 프론트엔드 테스트 코드 개발 (#90)
- 회원 기능 프론트엔드 테스트 코드 수정 (#91)
> [Refactor] 프론트엔드 테스트 코드 개발 (#88, #90)

- .idea/compiler.xml
- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/events/exception/EventAccessException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationDuplicateException.java
- backend/src/main/java/com/project/ssm/events/model/request/PatchEventReq.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- backend/src/main/java/com/project/ssm/meetingroom/service/MeetingRoomService.java
- backend/src/main/resources/application.yml
> [Refactor] 회의실, 일정 에러코드 리팩토링 (#28, #10)

- frontend/src/components/MeetingRoomComponent.vue
> [Refactor] 회의실 목록 불러오기 기능 수정

- backend/src/main/java/com/project/ssm/config/web/WebConfig.java
- backend/src/test/java/com/project/ssm/events/controller/EventControllerTest.java
- frontend/nginx/default.conf
- frontend/src/stores/useStompStore.js
- 웹 소켓 연결 코드 수정
- nginx conf.d 설정 파일에서 https 일때 헤더 추가
> [Refactor] 웹 소켓 연결 및 nginx conf.d 설정 파일 수정

- frontend/nginx/default.conf
- frontend/src/stores/useMainStore.js
- Nginx 타임아웃 시간 10분으로 변경
- Buffer 삭제
- Sse 연결이 되면 연결재시도 횟수 0으로 초기화
> [Refacotr] Nginx 설정 변경 및 open 이벤트 리스너 추가

- frontend/Dockerfile
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
> [Refactor] 채팅 입력 시 시간 반영 안되는 문제 해결

- frontend/public/js/addEvent.js
- frontend/src/stores/useMemberStore.js
> [Refactor] Member기능 예외처리 수정

- frontend/package-lock.json
- frontend/package.json
- frontend/tests/integrated/index.js
> [Refactor] 셀레니움을 활용한 통합 테스트 코드 작성

- frontend/src/stores/useMemberStore.js
> [Refactor] 멤버 프론트 에러코드 수정

- backend/src/main/java/com/project/ssm/chat/repository/querydsl/MessageRepositoryCustomImpl.java
- frontend/src/stores/useMessageStore.js
> [Refactor] 채팅 load 시 정렬 문제 해결

- backend/src/main/java/com/project/ssm/events/exception/EventAccessException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationDuplicateException.java
- backend/src/main/java/com/project/ssm/events/model/entity/Event.java
- backend/src/main/java/com/project/ssm/events/service/EventService.java
- backend/src/main/java/com/project/ssm/meetingroom/service/MeetingRoomService.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/public/js/addEvent.js
- frontend/public/js/editEvent.js
- frontend/public/js/main.js
- frontend/src/components/MeetingRoomComponent.vue
- frontend/src/stores/useMeetingRoomStore.js
- frontend/src/stores/useMemberStore.js
- 일정 관련 기능 예외 처리 코드를 추가
- 회의실 관련 기능 예외 처리 코드를 추가
- 백엔드 Service 코드에서 예외 처리 수정
- 사용하지 않는 예외 처리 코드를 삭제
>  [Refactor] 예외 처리 코드 추가 및 코드 리펙터링

- frontend/public/js/addEvent.js
- frontend/public/js/editEvent.js
- frontend/public/js/main.js
- frontend/src/components/CalendarComponent.vue
- frontend/src/components/ChatSearchComponent.vue
- frontend/src/components/CreateChatRoomComponent.vue
- frontend/src/components/FilterComponent.vue
- frontend/src/components/MeetingRoomModalComponent.vue
- frontend/src/components/MemberSearchComponent.vue
- frontend/src/components/ReservationComponent.vue
- frontend/src/components/SidebarComponent.vue
- frontend/src/pages/ChangeInfoPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/SignUpPage.vue
- frontend/src/router/index.js
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMeetingRoomStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 성공 응답에 대한 코드를 추가
- 각각의 에러 코드에 대한 예외 처리 코드를 추가
> [Refactor] 전체적인 예외 처리 코드 추가

- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- frontend/public/js/addEvent.js
- frontend/public/js/editEvent.js
- frontend/public/js/main.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMemberStore.js
- 로그인, 회의실 조회 시 성공코드 미스매치 해결
- public/js에 있는 Jquery 성공 및 예외처리 코드 수정
- profileImage 응답 시 BaseResponse로 응답하게 수정
- 멤버 조회 성공 시 성공코드 MEMBER_007로 수정
> [Refactor] 예외처리 적용 후 기능에러 해결

- backend/src/main/java/com/project/ssm/member/model/response/GetProfileImageRes.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- backend/src/main/java/com/project/ssm/search/service/SearchService.java
- frontend/src/components/CreateChatRoomComponent.vue
- frontend/src/components/MemberSearchComponent.vue
- frontend/src/stores/useMainStore.js
- 회원가입, 중복아이디 확인 하는 코드 수정
- profileImage 없을 때 발생하는 에러 해결
- 이름으로 회원 찾을 때 BaseResponse로 응답하게 해결
- 채팅방 생성 시 생성하기, 취소하기 css 색깔 변경
> [Refactor] 예외처리 적용 후 기능에러 해결2

- backend/src/main/java/com/project/ssm/member/service/MemberService.java
> [Refactor] 중복아이디, 회원가입 예외 수정

- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/member/service/MemberService.java
- backend/src/main/java/com/project/ssm/search/exception/Exception.java
- backend/src/main/java/com/project/ssm/search/service/SearchService.java
- frontend/.env.development
- frontend/src/components/CalendarComponent.vue
- frontend/src/components/MemberSearchComponent.vue
- frontend/src/pages/MainPage.vue
- frontend/src/stores/useChatRoomStore.js
- frontend/src/stores/useMainStore.js
- frontend/src/stores/useMeetingRoomStore.js
- frontend/src/stores/useMemberStore.js
- frontend/src/stores/useMessageStore.js
- frontend/src/stores/useStompStore.js
- 에러 코드 명 수정
- 채팅방 접속하지 않았을 때 채팅을 입력할 수 없게 disable 처리
>  [Refactor] 전체적인 에러 코드 수정

- backend/src/main/java/com/project/ssm/common/error/ErrorCode.java
- backend/src/main/java/com/project/ssm/events/exception/EventAccessException.java
- backend/src/main/java/com/project/ssm/events/exception/EventNotFoundException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationAccessException.java
- backend/src/main/java/com/project/ssm/events/exception/ReservationNotFoundException.java
- backend/src/main/java/com/project/ssm/meetingroom/exception/MeetingDuplicateException.java
- backend/src/main/java/com/project/ssm/meetingroom/exception/MeetingRoomNotFoundException.java
- 예외 처리 코드에서 매개 변수를 String.format으로 추가
- 에러 코드에서 안 맞는 부분 수정
> [Refactor] 전체적인 에러 코드 수정

- cicd/README.md
> [Fix] CI/CD 리드미 파일 수정

- frontend/src/stores/useMeetingRoomStore.js
- frontend/src/stores/useMessageStore.js
- 회의실 조회 예외처리 에러 수정
- 채팅컴포넌트 프로필 이미지 에러해결
>  채팅컴포넌트 프로필이미지, 회의실 에러 해결

- backend/src/main/java/com/project/ssm/utils/CurrentMeetingRoom.java
> [Refactor] 현재 회의실 조회 기능 리팩토링
